queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=build

pull_request_rules:

  - name: Label dependency-update PRs
    conditions:
      - or:
        - author~=^dependabot(|-preview)\[bot\]$
        - and:
          - author=fdietze
          - body~=Have a fantastic day writing Scala
    actions:
      label:
        add: [dependencies, scala]

  - name: Merge dependency-update PRs
    conditions:
      - and:
        - label=dependencies
        - base=master
        - check-success=build
    actions:
      queue:
        name: default
        method: squash
