queue_rules:
  - name: default
    queue_conditions:
      - and:
          - label=dependencies
          - base=master
          - check-success=build
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=build
    merge_method: squash

pull_request_rules:

  - name: Label dependency-update PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependencies, scala]
  - name: Merge dependency-update PRs
    conditions: []
    actions:
      queue:
