queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=build

pull_request_rules:

  - name: Label dependency-update PRs
    conditions:
      - or:
        - author=dependabot
        - author=scala-steward
    actions:
      label:
        add: [dependency-update]

  - name: Merge dependency-update PRs
    conditions:
      - and:
        - or:
          - author=dependabot
          - author=scala-steward
        - base=master
        - check-success=build
    actions:
      queue:
        name: default
        method: squash
